# -*- coding: utf-8 -*-
"""C++.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_9nSxr6FGvn_OsDVFprrVmqrdettqOn
"""

#include <iostream>
using namespace std;
int main(){
    int scores[6] = {26,49,98,87,62,75};
    int odds = 0;


    for (int i = 0; i < 6; ++i){
        if (scores[i] % 2 != 0){
            odds += scores[i];
        }
    }
    cout<< "The scores with the odd numbers combined is = " <<odds;
}