# -*- coding: utf-8 -*-
"""Example1.c++

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_9nSxr6FGvn_OsDVFprrVmqrdettqOn

C++ (AREA OF THE RECTANGLE)
"""

#include <iostream>
using namespace std;

int main(int argc, char** argv){
    int length, width, area;

    cout << "Please enter the length of the rectangle in cm: ";
    cin >> length;
    cout << "Please enter the width of the rectangle in cm: ";
    cin >> width;
    area = length * width;
    cout << "The area of the rectangle is " << area <<" cm";
}